# Generated by Django 5.2.8 on 2025-12-06 09:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_user_products_count'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='estimated_stock_out',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
